<?php

use CRM_Memberships_ExtensionUtil as E;

/**
 * Form controller class
 *
 * @see https://docs.civicrm.org/dev/en/latest/framework/quickform/
 */
class CRM_Memberships_Form_Registration extends CRM_Contribute_Form_AbstractEditPayment {
  public $_allRelatedContact = [];
  public $_selectedRelatedContact = [];
  public $_membershipTypeContactMapping = [];

  /**
   * Current payment processor including a copy of the object in 'object' key.
   *
   * @var array
   */
  public $_paymentProcessor;

  /**
   * Available recurring processors.
   *
   * @var array
   */
  public $_recurPaymentProcessors = [];

  /**
   * Is this a backoffice form
   *
   * @var bool
   */
  public $isBackOffice = TRUE;


  /**
   * The params submitted by the form and computed by the app
   *
   * @var array
   */
  public $_params = [];

  /**
   * The params submitted by the form and computed by the app
   *
   * @var array
   */
  public $_status = [];

  public function preProcess() {
    $this->_contactID = $this->getLoggedInUserContactID();
    $this->set('cid', $this->_contactID);

    $smarty = CRM_Core_Smarty::singleton();
    $wizard = $smarty->get_template_vars('wizard');
    $wizard['style']['showTitle'] = 0;
    $smarty->assign_by_ref('wizard', $wizard);

    $this->setTitle('Membership Payment');
    parent::preProcess(); // TODO: Change the autogenerated stub
  }

  public function buildQuickForm() {
  }

  public function postProcess() {
    $values = $this->exportValues();
    parent::postProcess();
  }
}
